# Generated by Django 3.2.5 on 2021-07-29 12:47

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('idAdministrateur', models.IntegerField(primary_key=True, serialize=False)),
                ('loginAdmin', models.CharField(max_length=20)),
                ('passwordAdmin', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('idCategorie', models.IntegerField(primary_key=True, serialize=False)),
                ('libelleCategorie', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.IntegerField(primary_key=True, serialize=False)),
                ('emailClient', models.EmailField(max_length=254)),
                ('loginClient', models.CharField(max_length=20)),
                ('passwordClient', models.CharField(max_length=24)),
                ('adresseClient', models.CharField(max_length=50)),
                ('telephoneClient', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('nomClient', models.CharField(max_length=50)),
                ('prenomClient', models.CharField(max_length=50)),
                ('dateDeNaissanceClient', models.DateField(blank=True, null=True)),
                ('avatarClient', models.ImageField(blank=True, null=True, upload_to=True)),
                ('descriptionClient', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('idFacture', models.IntegerField(primary_key=True, serialize=False)),
                ('datePaiementFacture', models.DateTimeField(auto_now_add=True)),
                ('prixHtFacture', models.FloatField()),
                ('totalHtFacture', models.FloatField()),
                ('totalTtc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ModeDeLivraiaon',
            fields=[
                ('idModeDeLivraison', models.IntegerField(primary_key=True, serialize=False)),
                ('libelleModeDeLivraison', models.CharField(max_length=50)),
                ('descriptionModeDeLivraison', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ModeDePaiement',
            fields=[
                ('idModeDePaiement', models.IntegerField(primary_key=True, serialize=False)),
                ('libelleModeDePaiement', models.CharField(max_length=50)),
                ('descriptionModeDePaiement', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('idCommande', models.IntegerField(primary_key=True, serialize=False)),
                ('dateAjoutCommande', models.DateTimeField(auto_now_add=True)),
                ('descriptionCommande', models.CharField(max_length=256)),
                ('modeDeLivraisonCommande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entities.modedelivraiaon')),
                ('modeDePaiementCommande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entities.modedepaiement')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('idArticle', models.IntegerField(primary_key=True, serialize=False)),
                ('nomArticle', models.CharField(max_length=50)),
                ('descriptionArticle', models.CharField(max_length=256)),
                ('quantiteArticle', models.IntegerField()),
                ('prixArticle', models.FloatField()),
                ('dateAjoutArticle', models.DateTimeField(auto_now_add=True)),
                ('categorieArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entities.categorie')),
            ],
        ),
    ]
