# Generated by Django 3.2.5 on 2021-07-29 13:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephoneClient',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
