# Generated by Django 3.2.5 on 2021-07-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0002_alter_client_telephoneclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='emailClient',
            field=models.CharField(max_length=50),
        ),
    ]
