# Generated by Django 3.2.5 on 2021-07-29 13:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0003_alter_client_emailclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatarClient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephoneClient',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
