# Generated by Django 3.2.5 on 2021-07-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0004_auto_20210729_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur',
            name='idAdministrateur',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='idArticle',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='idCategorie',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='idClient',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='idCommande',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facture',
            name='idFacture',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modedelivraiaon',
            name='idModeDeLivraison',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modedepaiement',
            name='idModeDePaiement',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
