# Generated by Django 3.2.5 on 2021-07-29 13:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0005_auto_20210729_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephoneClient',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
