# Generated by Django 3.2.5 on 2021-07-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0006_alter_client_telephoneclient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModeDeLivraiaon',
            new_name='ModeDeLivraison',
        ),
    ]
