# Generated by Django 3.2.5 on 2021-08-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0007_rename_modedelivraiaon_modedelivraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imageArticle',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='idAdministrateur',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='idArticle',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='idCategorie',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='avatarClient',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='idClient',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commande',
            name='idCommande',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facture',
            name='idFacture',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modedelivraison',
            name='idModeDeLivraison',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modedepaiement',
            name='idModeDePaiement',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
