# Generated by Django 3.2.5 on 2021-08-06 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Entities', '0011_facture_clientfacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dateDeCreationDuCompte',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=123456789, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
